<a href="https://colab.research.google.com/github/thobitz/PricingTest/blob/main/MCDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MCDemo

Monte Carlo Demo


In [1]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt


In [2]:
n = 1_000_000 # # Scenarios
S = 8
K = 10
sigma = .2
T = 1.5
r = 0.05

In [3]:
S_T = S * np.exp(((r-sigma**2/2.0)*T) + (sigma * np.sqrt(T) * np.random.normal(0, 1, size=n)))
C = np.maximum(S_T - K, 0).mean()*np.exp(-r*T)
C


np.float64(0.3528720598541143)

In [4]:
d1 = (np.log(S/K) + (r+sigma**2/2.0)*T)/(sigma*np.sqrt(T))
d2 = d1 - sigma*np.sqrt(T)
C_bs = S*st.norm.cdf(d1) - K*np.exp(-r*T)*st.norm.cdf(d2)
C_bs

np.float64(0.35174963554263483)

# Multiple products

In [5]:
K = np.linspace(6,12,61).reshape(-1,1)
K

array([[ 6. ],
       [ 6.1],
       [ 6.2],
       [ 6.3],
       [ 6.4],
       [ 6.5],
       [ 6.6],
       [ 6.7],
       [ 6.8],
       [ 6.9],
       [ 7. ],
       [ 7.1],
       [ 7.2],
       [ 7.3],
       [ 7.4],
       [ 7.5],
       [ 7.6],
       [ 7.7],
       [ 7.8],
       [ 7.9],
       [ 8. ],
       [ 8.1],
       [ 8.2],
       [ 8.3],
       [ 8.4],
       [ 8.5],
       [ 8.6],
       [ 8.7],
       [ 8.8],
       [ 8.9],
       [ 9. ],
       [ 9.1],
       [ 9.2],
       [ 9.3],
       [ 9.4],
       [ 9.5],
       [ 9.6],
       [ 9.7],
       [ 9.8],
       [ 9.9],
       [10. ],
       [10.1],
       [10.2],
       [10.3],
       [10.4],
       [10.5],
       [10.6],
       [10.7],
       [10.8],
       [10.9],
       [11. ],
       [11.1],
       [11.2],
       [11.3],
       [11.4],
       [11.5],
       [11.6],
       [11.7],
       [11.8],
       [11.9],
       [12. ]])

In [14]:
C = [np.maximum(S * np.exp(((r-sigma**2/2.0)*T) + (sigma * np.sqrt(T) * np.random.normal(0, 1, size=n))) - K_current, 0).mean()*np.exp(-r*T) for K_current in K]

In [15]:
C

[np.float64(2.4817081584233938),
 np.float64(2.400086232145894),
 np.float64(2.319363292924647),
 np.float64(2.2361111387213213),
 np.float64(2.1514777896895128),
 np.float64(2.072385745807661),
 np.float64(1.9943323540282643),
 np.float64(1.920173287866669),
 np.float64(1.845143009924608),
 np.float64(1.7750181505255977),
 np.float64(1.6969950263834632),
 np.float64(1.6305679013836092),
 np.float64(1.5592934821113575),
 np.float64(1.4922148392318502),
 np.float64(1.4262433403096502),
 np.float64(1.3635607925092512),
 np.float64(1.3016584196273826),
 np.float64(1.2424306396795581),
 np.float64(1.187414611569263),
 np.float64(1.1305067530242787),
 np.float64(1.076315574596203),
 np.float64(1.02302478760542),
 np.float64(0.9751132062734061),
 np.float64(0.9247111722744936),
 np.float64(0.877434429625471),
 np.float64(0.8329567120321112),
 np.float64(0.7902995799172745),
 np.float64(0.7466833047400913),
 np.float64(0.7091892068295589),
 np.float64(0.6716123689360621),
 np.float64(0.634252

In [18]:
S_T = S * np.exp(((r-sigma**2/2.0)*T) + (sigma * np.sqrt(T) * np.random.normal(0, 1, size=(K.shape[0],n))))
C = np.maximum(S_T - K, 0).mean(axis=1)*np.exp(-r*T)

In [19]:
C

array([2.4813661 , 2.39630966, 2.31850166, 2.23220379, 2.1530948 ,
       2.07530492, 1.997785  , 1.92073749, 1.84708555, 1.77154676,
       1.69689661, 1.6283355 , 1.56250279, 1.49213119, 1.4295817 ,
       1.36668096, 1.30261081, 1.24220582, 1.18671926, 1.13023854,
       1.07674638, 1.02348185, 0.97403833, 0.92320087, 0.87570804,
       0.83165304, 0.78864282, 0.74895363, 0.70794827, 0.67182498,
       0.63513052, 0.59973869, 0.56757736, 0.53423814, 0.5062516 ,
       0.47628193, 0.4465451 , 0.42282623, 0.39778899, 0.3750236 ,
       0.35094528, 0.33108657, 0.30966234, 0.29072244, 0.27365445,
       0.25646073, 0.24008302, 0.22620076, 0.21130231, 0.19904213,
       0.18594045, 0.17337096, 0.16184399, 0.15180816, 0.14164815,
       0.13411063, 0.12380391, 0.11639996, 0.10830228, 0.09973732,
       0.09458687])

In [10]:
d1 = (np.log(S/K) + (r+sigma**2/2.0)*T)/(sigma*np.sqrt(T))
d2 = d1 - sigma*np.sqrt(T)
C_bs = S*st.norm.cdf(d1) - K*np.exp(-r*T)*st.norm.cdf(d2)
C_bs

array([[2.48332805],
       [2.39915736],
       [2.31606355],
       [2.23412144],
       [2.15340445],
       [2.07398403],
       [1.99592904],
       [1.91930528],
       [1.84417495],
       [1.77059629],
       [1.69862312],
       [1.62830459],
       [1.55968486],
       [1.49280291],
       [1.42769242],
       [1.36438164],
       [1.30289335],
       [1.24324493],
       [1.18544835],
       [1.12951031],
       [1.07543239],
       [1.0232112 ],
       [0.97283864],
       [0.92430208],
       [0.87758464],
       [0.83266548],
       [0.78952007],
       [0.74812047],
       [0.70843567],
       [0.67043186],
       [0.63407275],
       [0.59931986],
       [0.56613282],
       [0.53446963],
       [0.50428697],
       [0.47554042],
       [0.44818475],
       [0.42217411],
       [0.3974623 ],
       [0.37400293],
       [0.35174964],
       [0.33065624],
       [0.31067691],
       [0.29176634],
       [0.27387982],
       [0.2569734 ],
       [0.24100394],
       [0.225

In [11]:
K = np.repeat(K, 100).reshape(-1,1)
K

array([[ 6.],
       [ 6.],
       [ 6.],
       ...,
       [12.],
       [12.],
       [12.]])