<a href="https://colab.research.google.com/github/thobitz/PricingTest/blob/main/MCDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MCDemo

Monte Carlo Demo


In [1]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt


In [2]:
n = 1_000_000 # # Scenarios
S = 8
K = 10
sigma = .2
T = 1.5
r = 0.05

In [3]:
S_T = S * np.exp(((r-sigma**2/2.0)*T) + (sigma * np.sqrt(T) * np.random.normal(0, 1, size=n)))
C = np.maximum(S_T - K, 0).mean()*np.exp(-r*T)
C


np.float64(0.3514277153125944)

In [4]:
d1 = (np.log(S/K) + (r+sigma**2/2.0)*T)/(sigma*np.sqrt(T))
d2 = d1 - sigma*np.sqrt(T)
C_bs = S*st.norm.cdf(d1) - K*np.exp(-r*T)*st.norm.cdf(d2)
C_bs

np.float64(0.35174963554263483)

# Multiple products

In [17]:
K = np.linspace(6,12,61).reshape(-1,1)
K

array([[ 6. ],
       [ 6.1],
       [ 6.2],
       [ 6.3],
       [ 6.4],
       [ 6.5],
       [ 6.6],
       [ 6.7],
       [ 6.8],
       [ 6.9],
       [ 7. ],
       [ 7.1],
       [ 7.2],
       [ 7.3],
       [ 7.4],
       [ 7.5],
       [ 7.6],
       [ 7.7],
       [ 7.8],
       [ 7.9],
       [ 8. ],
       [ 8.1],
       [ 8.2],
       [ 8.3],
       [ 8.4],
       [ 8.5],
       [ 8.6],
       [ 8.7],
       [ 8.8],
       [ 8.9],
       [ 9. ],
       [ 9.1],
       [ 9.2],
       [ 9.3],
       [ 9.4],
       [ 9.5],
       [ 9.6],
       [ 9.7],
       [ 9.8],
       [ 9.9],
       [10. ],
       [10.1],
       [10.2],
       [10.3],
       [10.4],
       [10.5],
       [10.6],
       [10.7],
       [10.8],
       [10.9],
       [11. ],
       [11.1],
       [11.2],
       [11.3],
       [11.4],
       [11.5],
       [11.6],
       [11.7],
       [11.8],
       [11.9],
       [12. ]])

In [19]:
%%timeit
C = [np.maximum(S * np.exp(((r-sigma**2/2.0)*T) + (sigma * np.sqrt(T) * np.random.normal(0, 1, size=n))) - K_current, 0).mean()*np.exp(-r*T) for K_current in K]

3.35 s ± 474 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
C

[np.float64(2.4815206248086628),
 np.float64(2.0753635795485392),
 np.float64(1.6965098390134004),
 np.float64(1.3668258814682692),
 np.float64(1.0738557074152728),
 np.float64(0.830934100152078),
 np.float64(0.6326541799181868),
 np.float64(0.4761982566059994),
 np.float64(0.35061848538091184),
 np.float64(0.25497584715212535),
 np.float64(0.18624871234247148),
 np.float64(0.13341898359487156),
 np.float64(0.09385562356715986)]

In [22]:
%%timeit
S_T = S * np.exp(((r-sigma**2/2.0)*T) + (sigma * np.sqrt(T) * np.random.normal(0, 1, size=(K.shape[0],n))))
C = np.maximum(S_T - K, 0).mean(axis=0)*np.exp(-r*T)

3.4 s ± 353 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
C

[np.float64(2.4815206248086628),
 np.float64(2.0753635795485392),
 np.float64(1.6965098390134004),
 np.float64(1.3668258814682692),
 np.float64(1.0738557074152728),
 np.float64(0.830934100152078),
 np.float64(0.6326541799181868),
 np.float64(0.4761982566059994),
 np.float64(0.35061848538091184),
 np.float64(0.25497584715212535),
 np.float64(0.18624871234247148),
 np.float64(0.13341898359487156),
 np.float64(0.09385562356715986)]

In [113]:
d1 = (np.log(S/K) + (r+sigma**2/2.0)*T)/(sigma*np.sqrt(T))
d2 = d1 - sigma*np.sqrt(T)
C_bs = S*st.norm.cdf(d1) - K*np.exp(-r*T)*st.norm.cdf(d2)
C_bs

array([2.48332805, 1.69862312, 1.07543239, 0.63407275, 0.35174964,
       0.18566769, 0.09422648])

In [125]:
K = np.repeat(K, 100).reshape(-1,1)
K

array([[ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
      